In [73]:
#Librerias necesarias
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [74]:
#Cargar dataset
ruta='/content/drive/MyDrive/U/Fundamentos de Ciencia de Datos/Titanic/titanic.csv'
df = pd.read_csv(ruta)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [75]:
#Cantidad de filas y columnas
df.shape

(891, 12)

In [76]:
#Analizar datos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [77]:
#Ver si cuenta con datos nulos
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [78]:
print(df["Survived"].unique())
print(df["Sex"].unique())
print(df["Pclass"].unique())
print(df["Embarked"].unique())

[0 1]
['male' 'female']
[3 1 2]
['S' 'C' 'Q' nan]

In [79]:
df_clean=df.copy()

In [80]:
df_clean["Age"] = df_clean["Age"].fillna(df_clean["Age"].median())

In [81]:
df_clean["Embarked"] = df_clean["Embarked"].fillna(
    df_clean["Embarked"].mode()[0]
)

In [82]:
df_clean["Cabin"] = df_clean["Cabin"].fillna("None")

In [83]:
df_clean.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [84]:
def limpiar_ticket_simple(ticket):
  ticket = str(ticket).strip()

  # Si tiene un espacio, nos quedamos únicamente con la última parte (el número)
  if ' ' in ticket:
    return ticket.rsplit(' ', 1)[-1]

  # Si es solo número o no tiene espacios, lo dejamos tal cual
  return ticket


# Aplicar la función directamente sobre la columna Ticket
df_clean['Ticket'] = df_clean['Ticket'].apply(limpiar_ticket_simple)

In [85]:
df_clean.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,21171,7.2500,None,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,3101282,7.9250,None,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,None,S

In [97]:
# 1. Filtramos mujeres de primera clase (Rose)
rose_subset = df_clean[
    (df_clean['Sex'] == 'female') &
    (df_clean['Pclass'] == 1)
]

# 2. Filtramos hombres de tercera clase (Jack)
jack_subset = df_clean[
    (df_clean['Sex'] == 'male') &
    (df_clean['Pclass'] == 3)
]

# 3. Calculamos las tasas de supervivencia
tasa_rose = rose_subset['Survived'].mean() * 100
tasa_jack = jack_subset['Survived'].mean() * 100

# 4. Mostramos los resultados
print("=== COMPARACIÓN DE SUPERVIVENCIA ===\n")

print(f"Rose (mujeres de primera clase): {tasa_rose:.2f}%")
print(f"Jack (hombres de tercera clase): {tasa_jack:.2f}%")

print(f"\nPasajeras del grupo de Rose: {len(rose_subset)}")
print(f"Pasajeros del grupo de Jack: {len(jack_subset)}")

=== COMPARACIÓN DE SUPERVIVENCIA ===

Rose (mujeres de primera clase): 96.81%
Jack (hombres de tercera clase): 13.54%

Pasajeras del grupo de Rose: 94
Pasajeros del grupo de Jack: 347

In [105]:
print("=== CONCLUSIÓN ===\n")
print(f"1. El grupo de Rose (primera clase, mujeres) representa la seguridad de la puerta, con una supervivencia del {tasa_rose:.2f}%.")
print("2. Si Jack se sube a la puerta con Rose, adopta este mismo entorno seguro de supervivencia.")
print(f"3. Por lo tanto, la probabilidad de Jack cambia de un bajo 13.54% a un casi seguro {tasa_rose:.2f}%.")
print("\nResultado final: SÍ, SE HUBIERA SALVADO.")

=== CONCLUSIÓN ===

1. El grupo de Rose (primera clase, mujeres) representa la seguridad de la puerta, con una supervivencia del 96.81%.
2. Si Jack se sube a la puerta con Rose, adopta este mismo entorno seguro de supervivencia.
3. Por lo tanto, la probabilidad de Jack cambia de un bajo 13.54% a un casi seguro 96.81%.

Resultado final: SÍ, SE HUBIERA SALVADO.